export interface StylePropertyConfig {
  id: string;
  label: string;
  prefix: string;
  values: string[];
  group?: string;
}

export const SPACING_PROPS: StylePropertyConfig[] = [
  {
    id: "margin",
    label: "margin",
    prefix: "m-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
      "32",
      "48",
      "64",
      "auto",
    ],
  },
  {
    id: "margin-top",
    label: "margin-top",
    prefix: "mt-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
      "auto",
    ],
  },
  {
    id: "margin-right",
    label: "margin-right",
    prefix: "mr-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
      "auto",
    ],
  },
  {
    id: "margin-bottom",
    label: "margin-bottom",
    prefix: "mb-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
      "auto",
    ],
  },
  {
    id: "margin-left",
    label: "margin-left",
    prefix: "ml-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
      "auto",
    ],
  },
  {
    id: "padding",
    label: "padding",
    prefix: "p-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
      "32",
      "48",
      "64",
    ],
  },
  {
    id: "padding-top",
    label: "padding-top",
    prefix: "pt-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
    ],
  },
  {
    id: "padding-right",
    label: "padding-right",
    prefix: "pr-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
    ],
  },
  {
    id: "padding-bottom",
    label: "padding-bottom",
    prefix: "pb-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
    ],
  },
  {
    id: "padding-left",
    label: "padding-left",
    prefix: "pl-",
    values: [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "8",
      "10",
      "12",
      "16",
      "20",
      "24",
    ],
  },
];

export const SIZING_PROPS: StylePropertyConfig[] = [
  {
    id: "width",
    label: "width",
    prefix: "w-",
    group: "width",
    values: [
      "auto",
      "full",
      "1/2",
      "1/3",
      "2/3",
      "1/4",
      "3/4",
      "12",
      "24",
      "32",
      "48",
      "64",
      "96",
    ],
  },
  {
    id: "height",
    label: "height",
    prefix: "h-",
    group: "height",
    values: [
      "auto",
      "full",
      "12",
      "16",
      "20",
      "24",
      "32",
      "40",
      "48",
      "56",
      "64",
      "80",
      "96",
    ],
  },
  {
    id: "min-width",
    label: "min-width",
    prefix: "min-w-",
    values: ["0", "[100px]", "[200px]", "[300px]", "full"],
  },
  {
    id: "max-width",
    label: "max-width",
    prefix: "max-w-",
    values: ["none", "xs", "sm", "md", "lg", "xl", "2xl", "full"],
  },
  {
    id: "min-height",
    label: "min-height",
    prefix: "min-h-",
    values: ["0", "[50px]", "[100px]", "[200px]", "full"],
  },
  {
    id: "max-height",
    label: "max-height",
    prefix: "max-h-",
    values: ["full", "[300px]", "[500px]", "screen"],
  },
  {
    id: "box-sizing",
    label: "box-sizing",
    prefix: "box-",
    group: "boxSizing",
    values: ["border", "content"],
  },
  {
    id: "aspect-ratio",
    label: "aspect-ratio",
    prefix: "aspect-",
    group: "aspectRatio",
    values: ["auto", "square", "video"],
  },
];

export const DISPLAY_PROPS: StylePropertyConfig[] = [
  {
    id: "display-mode",
    label: "display",
    prefix: "",
    group: "display",
    values: ["block", "inline-block", "inline", "flex", "grid", "none"],
  },
];

export const POSITION_PROPS: StylePropertyConfig[] = [
  {
    id: "position",
    label: "position",
    prefix: "",
    group: "position",
    values: ["static", "relative", "absolute", "fixed", "sticky"],
  },
  {
    id: "z-index",
    label: "z-index",
    prefix: "z-",
    values: ["auto", "0", "10", "20", "30", "40", "50", "999"],
  },
  {
    id: "inset",
    label: "inset",
    prefix: "inset-",
    values: ["auto", "0", "1", "2", "4", "8", "12", "16"],
  },
  {
    id: "top",
    label: "top",
    prefix: "top-",
    values: ["auto", "0", "1", "2", "4", "8", "12", "16"],
  },
  {
    id: "right",
    label: "right",
    prefix: "right-",
    values: ["auto", "0", "1", "2", "4", "8", "12", "16"],
  },
  {
    id: "bottom",
    label: "bottom",
    prefix: "bottom-",
    values: ["auto", "0", "1", "2", "4", "8", "12", "16"],
  },
  {
    id: "left",
    label: "left",
    prefix: "left-",
    values: ["auto", "0", "1", "2", "4", "8", "12", "16"],
  },
];

export const FLEXBOX_PROPS: StylePropertyConfig[] = [
  {
    id: "display",
    label: "display",
    prefix: "",
    group: "display",
    values: ["flex", "inline-flex"],
  },
  {
    id: "direction",
    label: "direction",
    prefix: "",
    group: "flexDirection",
    values: ["flex-row", "flex-col", "flex-wrap"],
  },
  {
    id: "align-items",
    label: "align-items",
    prefix: "",
    group: "alignment",
    values: [
      "items-start",
      "items-center",
      "items-end",
      "items-baseline",
      "items-stretch",
    ],
  },
  {
    id: "justify",
    label: "justify-content",
    prefix: "",
    group: "justify",
    values: [
      "justify-start",
      "justify-center",
      "justify-end",
      "justify-between",
      "justify-around",
      "justify-evenly",
    ],
  },
  {
    id: "align-self",
    label: "align-self",
    prefix: "",
    group: "alignSelf",
    values: [
      "self-auto",
      "self-start",
      "self-end",
      "self-center",
      "self-stretch",
      "self-baseline",
    ],
  },
  {
    id: "gap",
    label: "gap",
    prefix: "",
    group: "gap",
    values: [
      "gap-0",
      "gap-1",
      "gap-2",
      "gap-3",
      "gap-4",
      "gap-5",
      "gap-6",
      "gap-8",
      "gap-10",
      "gap-12",
      "gap-16",
    ],
  },
  {
    id: "flex-grow",
    label: "flex grow",
    prefix: "",
    group: "flexGrow",
    values: ["grow-0", "grow"],
  },
  {
    id: "flex-shrink",
    label: "flex shrink",
    prefix: "",
    group: "flexShrink",
    values: ["shrink-0", "shrink"],
  },
];

export const GRID_PROPS: StylePropertyConfig[] = [
  {
    id: "display",
    label: "display",
    prefix: "",
    group: "display",
    values: ["grid"],
  },
  {
    id: "cols",
    label: "columns",
    prefix: "grid-cols-",
    values: ["1", "2", "3", "4", "5", "6", "12"],
  },
  { id: "rows", label: "rows", prefix: "grid-rows-", values: ["1", "2", "3"] },
  {
    id: "gap",
    label: "gap",
    prefix: "",
    group: "gap",
    values: [
      "gap-0",
      "gap-1",
      "gap-2",
      "gap-4",
      "gap-6",
      "gap-8",
      "gap-10",
      "gap-12",
      "gap-16",
    ],
  },
  {
    id: "col-span",
    label: "column span",
    prefix: "col-span-",
    values: ["1", "2", "3", "4", "5", "6", "12", "full"],
  },
  {
    id: "row-span",
    label: "row span",
    prefix: "row-span-",
    values: ["1", "2", "3", "4", "5", "6", "full"],
  },
];

export const OVERFLOW_PROPS: StylePropertyConfig[] = [
  {
    id: "overflow",
    label: "overflow",
    prefix: "",
    group: "overflow",
    values: [
      "overflow-auto",
      "overflow-hidden",
      "overflow-scroll",
      "overflow-visible",
      "overflow-clip",
    ],
  },
  {
    id: "overflow-x",
    label: "overflow-x",
    prefix: "",
    group: "overflowX",
    values: [
      "overflow-x-auto",
      "overflow-x-hidden",
      "overflow-x-scroll",
      "overflow-x-visible",
      "overflow-x-clip",
    ],
  },
  {
    id: "overflow-y",
    label: "overflow-y",
    prefix: "",
    group: "overflowY",
    values: [
      "overflow-y-auto",
      "overflow-y-hidden",
      "overflow-y-scroll",
      "overflow-y-visible",
      "overflow-y-clip",
    ],
  },
  {
    id: "scroll-behavior",
    label: "scroll-behavior",
    prefix: "",
    group: "scrollBehavior",
    values: ["scroll-smooth", "scroll-auto"],
  },
  {
    id: "scroll-snap-type",
    label: "scroll-snap-type",
    prefix: "",
    group: "scrollSnapType",
    values: ["snap-none", "snap-x", "snap-y", "snap-both"],
  },
];

export const TYPOGRAPHY_STYLES_PROPS: StylePropertyConfig[] = [
  {
    id: "text-size",
    label: "text-size",
    prefix: "",
    group: "textSize",
    values: [
      "text-xs",
      "text-sm",
      "text-base",
      "text-lg",
      "text-xl",
      "text-2xl",
      "text-3xl",
      "text-4xl",
      "text-5xl",
      "text-6xl",
      "text-7xl",
    ],
  },
  {
    id: "font-family",
    label: "font-family",
    prefix: "",
    group: "fontFamily",
    values: ["font-sans", "font-serif", "font-mono"],
  },
  {
    id: "font-weight",
    label: "font-weight",
    prefix: "",
    group: "fontWeight",
    values: [
      "font-light",
      "font-normal",
      "font-medium",
      "font-semibold",
      "font-bold",
    ],
  },
  {
    id: "line-height",
    label: "line-height",
    prefix: "",
    group: "leading",
    values: [
      "leading-none",
      "leading-tight",
      "leading-snug",
      "leading-normal",
      "leading-relaxed",
      "leading-loose",
    ],
  },
  {
    id: "font-style",
    label: "font-style",
    prefix: "",
    values: ["italic", "not-italic"],
  },
];

export const TYPOGRAPHY_SPACING_PROPS: StylePropertyConfig[] = [
  {
    id: "text-align",
    label: "text-align",
    prefix: "",
    group: "textAlign",
    values: ["text-left", "text-center", "text-right", "text-justify"],
  },
  {
    id: "decoration",
    label: "text-decoration",
    prefix: "",
    values: ["underline", "line-through", "no-underline"],
  },
  {
    id: "transform",
    label: "text-transform",
    prefix: "",
    values: ["uppercase", "lowercase", "capitalize", "normal-case"],
  },
  {
    id: "tracking",
    label: "tracking",
    prefix: "",
    group: "tracking",
    values: [
      "tracking-tighter",
      "tracking-tight",
      "tracking-normal",
      "tracking-wide",
      "tracking-widest",
    ],
  },
];

export const COLOR_PROPS: StylePropertyConfig[] = [
  {
    id: "background-color",
    label: "background color",
    prefix: "bg-",
    values: [
      "transparent",
      "white",
      "stone-50",
      "stone-100",
      "stone-200",
      "stone-900",
      "stone-950",
      "rose-50",
      "rose-100",
      "rose-600",
      "amber-50",
      "amber-100",
      "amber-600",
      "amber-700",
      "amber-950",
      "emerald-50",
      "emerald-600",
      "emerald-950",
    ],
  },
  {
    id: "text-color",
    label: "text color",
    prefix: "text-",
    values: [
      "white",
      "black",
      "stone-800",
      "stone-100",
      "rose-600",
      "amber-600",
      "emerald-600",
    ],
  },
  {
    id: "border-color",
    label: "border color",
    prefix: "border-",
    values: [
      "transparent",
      "stone-200",
      "stone-300",
      "stone-800",
      "rose-200",
      "rose-600",
      "amber-600",
    ],
  },
  {
    id: "opacity",
    label: "opacity",
    prefix: "opacity-",
    values: [
      "0",
      "10",
      "20",
      "25",
      "30",
      "40",
      "50",
      "60",
      "70",
      "75",
      "80",
      "90",
      "95",
      "100",
    ],
  },
];

export const BORDER_PROPS: StylePropertyConfig[] = [
  {
    id: "rounding",
    label: "rounding/radius",
    prefix: "",
    group: "rounding",
    values: [
      "rounded-none",
      "rounded-sm",
      "rounded",
      "rounded-md",
      "rounded-lg",
      "rounded-xl",
      "rounded-2xl",
      "rounded-3xl",
      "rounded-full",
    ],
  },
  {
    id: "border-width",
    label: "border-width",
    prefix: "",
    group: "borderWidth",
    values: ["border-0", "border", "border-2", "border-4", "border-8"],
  },
  {
    id: "border-style",
    label: "border-style",
    prefix: "",
    values: ["border-solid", "border-dashed", "border-dotted"],
  },
  {
    id: "shadow",
    label: "box-shadow",
    prefix: "",
    group: "shadow",
    values: [
      "shadow-none",
      "shadow-sm",
      "shadow",
      "shadow-md",
      "shadow-lg",
      "shadow-xl",
      "shadow-2xl",
    ],
  },
];

export const TRANSITION_PROPS: StylePropertyConfig[] = [
  {
    id: "transition",
    label: "transition",
    prefix: "",
    values: [
      "transition-none",
      "transition-all",
      "transition-colors",
      "transition-opacity",
      "transition-transform",
    ],
  },
  {
    id: "duration",
    label: "duration",
    prefix: "",
    values: [
      "duration-75",
      "duration-100",
      "duration-150",
      "duration-200",
      "duration-300",
      "duration-500",
      "duration-700",
      "duration-1000",
    ],
  },
  {
    id: "easing",
    label: "easing",
    prefix: "",
    values: ["ease-linear", "ease-in", "ease-out", "ease-in-out"],
  },
];

export const ANIMATION_PROPS: StylePropertyConfig[] = [
  {
    id: "animation",
    label: "keyframe animation",
    prefix: "animate-",
    values: ["none", "fade-in", "pulse", "bounce", "spin", "ping"],
  },
  {
    id: "hover-scale",
    label: "hover scale",
    prefix: "",
    values: ["hover:scale-[1.03]", "hover:scale-[1.05]", "hover:scale-[1.10]"],
  },
  {
    id: "hover-rotate",
    label: "hover rotate",
    prefix: "",
    values: ["hover:rotate-1", "hover:rotate-3", "hover:rotate-6"],
  },
  {
    id: "hover-shadow",
    label: "hover shadow",
    prefix: "",
    values: [
      "hover:shadow-sm",
      "hover:shadow",
      "hover:shadow-md",
      "hover:shadow-lg",
      "hover:shadow-xl",
      "hover:shadow-2xl",
    ],
  },
  {
    id: "hover-opacity",
    label: "hover opacity",
    prefix: "",
    values: [
      "hover:opacity-10",
      "hover:opacity-25",
      "hover:opacity-50",
      "hover:opacity-75",
      "hover:opacity-90",
      "hover:opacity-100",
    ],
  },
];
